# Generated by Django 5.1.4 on 2025-02-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unprocessedsatelliteimage',
            name='cloud_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
