# Generated by Django 5.1.4 on 2025-02-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_unprocessedsatelliteimage_cloud_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='cloud_percentage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
