# Generated by Django 5.1.4 on 2025-02-13 02:32

from django.db import migrations

def create_statuses(apps, schema_editor):
    AnalysisRequestStatus = apps.get_model('api', 'AnalysisRequestStatus')
    statuses = [
        (1, 'Na fila', 'Na fila'),
        (2, 'Baixando imagens', 'Baixando imagens'),
        (3, 'Processando imagens', 'Processando imagens'),
        (4, 'Cancelada', 'Cancelada'),
        (5, 'Falha', 'Falha'),
        (6, 'Finalizada', 'Finalizada')
    ]
    for id, name, description in statuses:
        AnalysisRequestStatus.objects.create(id=id, name=name, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_analysis_cloud_percentage'),
    ]

    operations = [
        migrations.RunPython(create_statuses),
    ]
