version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/code
      - ./processing/credentials:/app/credentials:ro
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    env_file:
      - .env
    depends_on:
      - db